In [ ]:
print("Learning NumPy")


Learning NumPy


In [ ]:
#Create a NumPy array:

#1-D array:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)
print(type(arr1))

#2-D array:

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)


print(arr2.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
2


In [ ]:
#Check how many dimensions the arrays have:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#Get the first element from the following array:

arr = np.array([20, 2, 3, 4])

print(arr[0])

#add:
sum = arr[0]+arr[2]
print("sum is: ",sum)



20
sum is:  23


In [ ]:
#checking the value of a 2D matrix:
arr = np.array([[1,2,3], [6,7,8]])

print(arr.shape)
print('2nd element on 1st row: ', arr[0, 1])

(2, 3)
2nd element on 1st row:  2


In [ ]:
#checking the value of a 3D matrix:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape)
print(arr[0, 1, 2])

(2, 2, 3)
6


In [ ]:
#Slice elements index to index:
arr = np.array([1, 2, 3, 4, 5, 65, 7])

print(arr[1:6])

#Slice elements index to end:
print(arr[5:])

#Slice elements start to index:
print(arr[:5])

#Slice elements start to end:
print(arr[:])



[ 2  3  4  5 65]
[65  7]
[1 2 3 4 5]
[ 1  2  3  4  5 65  7]


In [ ]:
#data type of an array object:
arr1 = np.array([1, 2, 3, 4])

print(arr1.dtype)

arr2 = np.array(['apple', 'banana', 'cherry'])

print(arr2.dtype)

int64
<U6


In [7]:
#copy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print('main Array:',arr)
print('Copy array:',x)

main Array: [42  2  3  4  5]
Copy array: [1 2 3 4 5]


In [9]:
#view

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
#Reshape

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print('Reshape From 1-D to 2-D:\n',newarr)
newarr2 = arr.reshape(2, 3, 2)
print('Reshape From 1-D to 3-D:\n',newarr2)


Reshape From 1-D to 2-D:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshape From 1-D to 3-D:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
#Join

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [26]:
#Split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [30]:
#Searching in Arrays

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

#even index values
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

y = np.where(arr2%2 == 0)

print(y)

#odd index values
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

z = np.where(arr3%2 == 1)

print(z)

(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [35]:
#Sorting Arrays

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

#string array sort
arr1 = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr1))

#2-D array sort
arr2 = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr2))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


In [39]:
#shuffle
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 3 4 2 1]


In [50]:
#Simple Arithmetic

arr1 = np.array([10, 11, 12, 16, 14, 15])
arr2 = np.array([2, 11, 6, 8, 2, 3])
#Addition
newarr = np.add(arr1, arr2)
print('New array after addition:',newarr)

#Subtraction
newarr2 = np.subtract(arr1, arr2)
print('New array after Subtraction:',newarr2)

#Multiplication
newarr3 = np.multiply(arr1, arr2)
print('New array after Multiplication:',newarr3)

#Division
newarr4 = np.divide(arr1, arr2)
print('New array after Division:',newarr4)

#Remainder
newarr5 = np.mod(arr1, arr2)
print('New array after Remainder:',newarr5)


New array after addition: [12 22 18 24 16 18]
New array after Subtraction: [ 8  0  6  8 12 12]
New array after Multiplication: [ 20 121  72 128  28  45]
New array after Division: [5. 1. 2. 2. 7. 5.]
New array after Remainder: [0 0 0 0 0 0]


In [52]:
#Absolute Values
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)

print('New array after Absolute Values operations:',newarr)


New array after Absolute Values operations: [1 2 1 2 3 4]


In [57]:
#Rounding Decimals

#Truncation
arrT = np.trunc([-3.1666, 3.6667])

print(arrT)

#fix
arrF = np.fix([-3.1666, 3.6667])
print(arrF)

#rounding
arr = np.around(3.1666, 2)
print(arr)

#Floor
arr = np.floor([-3.1666, 3.6667])
print(arr)

#Ceil
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]
